"""Testes de integração do ambiente de migrations (ADR-012).

Validam que a infraestrutura do Alembic funciona contra PostgreSQL real:
`upgrade head` executa e `alembic check` não encontra divergência entre o
metadata da aplicação e o schema do banco.

Nesta fase não existe nenhuma revision — decisão do ADR-012 de não criar
migration artificial. O ciclo `upgrade → downgrade → upgrade` só ganhará teste
quando existir uma revision real, junto com a primeira SPEC.

Estes testes usam a API síncrona do Alembic (o `env.py` usa engine síncrono,
como o ADR permite), por isso não levam o marcador `asyncio`.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config as AlembicConfig

from urbanopay.core.config import Settings

REPO_ROOT = Path(__file__).resolve().parents[2]


def _alembic_config() -> AlembicConfig:
    """Configuração do Alembic com caminhos absolutos.

    O `script_location` do alembic.ini é relativo ao diretório de execução;
    aqui ele é fixado de forma absoluta para que o teste não dependa do cwd do
    pytest.
    """
    cfg = AlembicConfig(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option(
        "script_location",
        str(REPO_ROOT / "apps" / "api" / "src" / "urbanopay" / "db" / "migrations"),
    )
    return cfg


@pytest.mark.integration
def test_upgrade_head_executa(settings: Settings) -> None:
    """`alembic upgrade head` roda contra o banco de teste sem erro."""
    command.upgrade(_alembic_config(), "head")


@pytest.mark.integration
def test_alembic_check_sem_divergencia(settings: Settings) -> None:
    """`alembic check` não encontra diferença entre metadata e schema.

    Também prova o isolamento dos testes: o schema descartável
    `it_foundation` (quando existir em paralelo) não aparece na comparação,
    porque o env.py usa `include_schemas=False`.
    """
    command.upgrade(_alembic_config(), "head")
    # Levanta AutogenerateDiffsDetected se houver divergência.
    command.check(_alembic_config())
