"""Testes de integração do ambiente de migrations (ADR-012).

Validam que a infraestrutura do Alembic funciona contra PostgreSQL real:
`upgrade head` executa e `alembic check` não encontra divergência entre o
metadata da aplicação e o schema do banco.

Nesta fase não existe nenhuma revision — decisão do ADR-012 de não criar
migration artificial. O ciclo `upgrade → downgrade → upgrade` só ganhará teste
quando existir uma revision real, junto com a primeira SPEC.

Estes testes usam a API síncrona do Alembic (o `env.py` usa engine síncrono,
como o ADR permite), por isso não levam o marcador `asyncio`.
"""

from __future__ import annotations

import pytest
import sqlalchemy as sa
from alembic import command

from tests.integration.conftest import alembic_config
from urbanopay.core.config import Settings
from urbanopay.db.engine import build_database_url

# Os totais do conjunto de referência do MVP: 12 tarifas (5 linhas de ônibus ×
# 2 perfis + metrô × 2 perfis) e 1 regra de INTEGRATION (SPEC-001 §2, §5).
OFFICIAL_FARES_COUNT = 12
OFFICIAL_RULES_COUNT = 1


def _seed_counts(settings: Settings) -> tuple[int, int]:
    """Conta os registros de referência via engine síncrono descartável."""
    engine = sa.create_engine(build_database_url(settings))
    try:
        with engine.connect() as conn:
            fares = conn.execute(
                sa.text("SELECT count(*) FROM fares WHERE valid_from = :start"),
                {"start": "2026-01-01T00:00:00Z"},
            ).scalar_one()
            rules = conn.execute(sa.text("SELECT count(*) FROM fare_rules")).scalar_one()
        return int(fares), int(rules)
    finally:
        engine.dispose()


@pytest.mark.integration
def test_upgrade_head_executa(settings: Settings) -> None:
    """`alembic upgrade head` roda contra o banco de teste sem erro."""
    command.upgrade(alembic_config(), "head")


@pytest.mark.integration
def test_alembic_check_sem_divergencia(settings: Settings) -> None:
    """`alembic check` não encontra diferença entre metadata e schema.

    Com os models do fare registrados, esta é uma comparação real: qualquer
    divergência entre `models.py` e as migrations reprova aqui. Também prova o
    isolamento dos testes: o schema descartável `it_foundation` não aparece na
    comparação (`include_schemas=False` no env.py).
    """
    command.upgrade(alembic_config(), "head")
    # Levanta AutogenerateDiffsDetected se houver divergência.
    command.check(alembic_config())


@pytest.mark.integration
def test_ciclo_completo_upgrade_downgrade_base_upgrade(settings: Settings) -> None:
    """Reversibilidade completa: head → base → head (ADR-012).

    Prova a migration de schema e a de dados: após o ciclo, o banco contém
    exatamente o conjunto de referência do MVP.
    """
    cfg = alembic_config()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")

    fares, rules = _seed_counts(settings)
    assert fares == OFFICIAL_FARES_COUNT
    assert rules == OFFICIAL_RULES_COUNT


@pytest.mark.integration
def test_downgrade_um_passo_remove_somente_dados_de_referencia(settings: Settings) -> None:
    """`downgrade -1` a partir de head desfaz o seed sem tocar o schema."""
    cfg = alembic_config()
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "-1")

    engine = sa.create_engine(build_database_url(settings))
    try:
        with engine.connect() as conn:
            # O schema permanece: a tabela existe e está sem os dados de
            # referência.
            fares = conn.execute(sa.text("SELECT count(*) FROM fares")).scalar_one()
            rules = conn.execute(sa.text("SELECT count(*) FROM fare_rules")).scalar_one()
        assert int(fares) == 0
        assert int(rules) == 0
    finally:
        engine.dispose()

    command.upgrade(cfg, "head")
    fares_after, rules_after = _seed_counts(settings)
    assert fares_after == OFFICIAL_FARES_COUNT
    assert rules_after == OFFICIAL_RULES_COUNT
